name: wordle_api
description: Dart library for the Wordle game.
version: 0.1.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6

  very_good_analysis: ^5.1.0
